Rankup Message: "&eGRanks >> &aYou have successfully ranked up from %PreviousRank% -> %NewRank% and you payed &6%Amount%"
Prestige Message: "&eGRanks >> &aYou have successfully ranked up %Prestige% and you payed &6%Amount%"

Player Data:
